use crate::ui::assets::spacing;

use super::palette::*;
use super::semantic::*;

pub const ATELIER: Semantic = Semantic {
    background: Background {
        app: NEUTRAL_10,
        surface: NEUTRAL_15,
    },
    surface: Surface {
        elevated: NEUTRAL_11,
        panel: NEUTRAL_12,
        raised: NEUTRAL_14,
        field: NEUTRAL_15,
        control: NEUTRAL_20,
        placeholder: NEUTRAL_18,
        gradient_start: VIOLET_22,
        gradient_end: NEUTRAL_09,
    },
    content: Content {
        primary: WARM_91,
        primary_alt: WARM_91,
        active: WARM_91,
        secondary: WARM_73,
        secondary_alt: WARM_73,
        secondary_alt2: WARM_73,
        tertiary: WARM_51,
        tertiary_alt: WARM_51,
        tertiary_alt2: WARM_51,
        muted: WARM_51,
        muted_alt: WARM_51,
        muted_alt2: WARM_51,
        faint: WARM_40,
        faint_alt: WARM_40,
        disabled: WARM_51,
        disabled_alt: WARM_51,
        disabled_alt2: WARM_51,
        on_accent: BLACK,
        on_banner: WHITE_A75,
        on_control_disabled: WHITE_A30,
    },
    border: Border {
        subtle: WHITE_A12,
        field: NEUTRAL_30,
        drag: WHITE_A15,
    },
    accent: Accent {
        primary: VIOLET_62,
        hover: VIOLET_72,
        strong: VIOLET_49,
        strong_hover: VIOLET_55,
        control_active: VIOLET_62,
    },
    overlay: Overlay {
        hover_subtle: WHITE_A03,
        hover_row: WHITE_A06,
        hover_accent: VIOLET_62_A14,
        hover_item: WHITE_A10,
        selected: WHITE_A08,
        card_idle: WHITE_A025,
        card_hover: WHITE_A05,
        card_border_idle: WHITE_A10,
        card_border_hover: WHITE_A16,
        control_idle: WHITE_A10,
        control_hover: WHITE_A18,
        control_disabled: WHITE_A04,
        toggle_idle: WHITE_A08,
        toggle_hover: WHITE_A14,
        toggle_on_idle: WHITE_A22,
        toggle_on_hover: WHITE_A28,
        scrim_cover: BLACK_A40,
        scrim_strong: BLACK_A55,
        scrim_play: BLACK_A60,
    },
    elevation: Elevation {
        shadow: iced::Shadow {
            color: BLACK_A45,
            offset: iced::Vector::new(0.0, spacing::SP_8),
            blur_radius: spacing::SP_32,
        },
    },
    status: Status {
        liked: ROSE_64,
        cached: TEAL_57,
        error: CLAY_57,
    },
};
