use super::palette::*;
use super::semantic::*;

pub const ATELIER: Semantic = Semantic {
    background: Background {
        app: NEUTRAL_10,
        surface: SLATE_15,
    },
    surface: Surface {
        elevated: SLATE_10,
        panel: NEUTRAL_12,
        raised: SLATE_14,
        field: NEUTRAL_15,
        control: NEUTRAL_20,
        placeholder: NEUTRAL_18,
        gradient_start: VIOLET_22,
        gradient_end: SLATE_09,
    },
    content: Content {
        primary: WHITE,
        primary_alt: SLATE_85,
        active: NEUTRAL_82,
        secondary: SLATE_70,
        secondary_alt: SLATE_75,
        secondary_alt2: SLATE_65,
        tertiary: SLATE_60,
        tertiary_alt: NEUTRAL_60,
        tertiary_alt2: SLATE_55,
        muted: STEEL_50,
        muted_alt: SLATE_50,
        muted_alt2: STEEL_40,
        faint: SLATE_45,
        faint_alt: NEUTRAL_45,
        disabled: SLATE_35,
        disabled_alt: NEUTRAL_40,
        disabled_alt2: NEUTRAL_30,
        on_accent: BLACK,
        on_banner: WHITE_A75,
        on_control_disabled: WHITE_A30,
    },
    border: Border {
        subtle: WHITE_A12,
        field: NEUTRAL_30,
        drag: WHITE_A15,
    },
    accent: Accent {
        primary: VIOLET_74,
        hover: VIOLET_85,
        strong: VIOLET_55,
        strong_hover: VIOLET_62,
        control_active: VIOLET_62,
        tint: VIOLET_22,
    },
    overlay: Overlay {
        hover_subtle: WHITE_A03,
        hover_row: WHITE_A06,
        hover_item: WHITE_A10,
        selected: WHITE_A08,
        card_idle: WHITE_A025,
        card_hover: WHITE_A05,
        card_border_idle: WHITE_A10,
        card_border_hover: WHITE_A16,
        control_idle: WHITE_A10,
        control_hover: WHITE_A18,
        control_disabled: WHITE_A04,
        toggle_idle: WHITE_A08,
        toggle_hover: WHITE_A14,
        toggle_on_idle: WHITE_A22,
        toggle_on_hover: WHITE_A28,
        scrim_cover: BLACK_A40,
        scrim_strong: BLACK_A55,
        scrim_play: BLACK_A60,
        shadow: BLACK_A45,
    },
    status: Status {
        liked: CRIMSON,
        cached: MINT,
        error: SALMON,
    },
};
